### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by psychomad** [GONZOsint/Namechk#2]
Hello
I've got some false positive.
for example on twitter namechk told me exist but is not true, will be nice add some verification string, what you think?

**Comment by GONZOsint** [comment]
Thanks for notifying, I am aware of false positives. All come from the NameChk website, where they are also false positive.

I will correct the error in the future.
If you dare, you can do it yourself.

**Comment by psychomad** [comment]
Im working on it.. thanks for answer! :)

**Comment by GONZOsint** [comment]
Im doing the same tool on python, will be released soon. ;)

**Comment by jwoertink** [comment]
Hey, I'd love some help on these. I know some are showing false positives, but if you have some better ways to check these, I'm all ears!
