### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by ondrj** [GONZOsint/Namechk#4]
Hello,
it seems to check for usernames, but there are not link associated with particular account, see example:
![Screenshot from 2019-05-08 06-19-51](https://user-images.githubusercontent.com/37909418/57349185-788c4f00-7159-11e9-9da5-1ad264e06eb8.png)

**Comment by BaRRaKudaRain** [comment]
Hmmm... Strange bug. For first time try (sitename.domain/username)

-----Original Message-----

**Comment by pwningathtb** [comment]
Getting the same issue as well.

**Comment by dotwreck** [comment]
I know this is old, but I just came across this script and am searching my own user names. The script is not finding them on the sites I have accounts on...

**Comment by berkkivircik** [comment]
the issue still continues. any update?

**Comment by GONZOsint** [comment]
> the issue still continues. any update?

The tool no longer works properly. There are much better alternatives like Sherlock, Maigret or whatsmyname.
